
import React from 'react';
import { ParentReport, QuizResult } from '../types';

interface ParentReportViewProps {
  report: ParentReport;
  quizResult?: QuizResult | null;
}

export const ParentReportView: React.FC<ParentReportViewProps> = ({ report, quizResult }) => {
  return (
    <div className="bg-slate-900 text-white rounded-[2.5rem] p-8 lg:p-12 shadow-2xl border border-white/10 animate-fadeIn">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-12 border-b border-white/10 pb-8">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-indigo-600 rounded-2xl shadow-lg shadow-indigo-500/20">
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
          </div>
          <div>
            <h3 className="text-2xl font-black tracking-tight">Guardian Insights</h3>
            <p className="text-indigo-400 font-bold uppercase text-[10px] tracking-[0.2em]">Educational Consultation Report</p>
          </div>
        </div>

        {quizResult && (
          <div className="bg-white/5 border border-white/10 rounded-2xl px-6 py-4 flex items-center gap-6">
            <div className="text-center border-r border-white/10 pr-6">
              <span className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1">Performance</span>
              <span className="text-2xl font-black text-emerald-400">
                {Math.round((quizResult.score / quizResult.total) * 100)}%
              </span>
            </div>
            <div className="text-center">
              <span className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1">Questions</span>
              <span className="text-2xl font-black text-white">
                {quizResult.score}/{quizResult.total}
              </span>
            </div>
          </div>
        )}
      </div>

      <div className="grid md:grid-cols-2 gap-12">
        <div className="space-y-10">
          <section>
            <h4 className="text-xs font-black text-indigo-400 uppercase tracking-widest mb-4 flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
              Session Summary
            </h4>
            <p className="text-slate-300 leading-relaxed text-lg font-medium">
              {report.summary}
            </p>
          </section>

          <section>
            <h4 className="text-xs font-black text-indigo-400 uppercase tracking-widest mb-6 flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
              Learning Highlights
            </h4>
            <ul className="space-y-4">
              {report.highlights.map((highlight, idx) => (
                <li key={idx} className="flex gap-4 items-start bg-white/5 p-4 rounded-2xl border border-white/5">
                  <span className="flex-shrink-0 w-6 h-6 bg-indigo-500 rounded-full flex items-center justify-center text-[10px] font-black">
                    {idx + 1}
                  </span>
                  <span className="text-slate-300 font-medium">{highlight}</span>
                </li>
              ))}
            </ul>
          </section>
        </div>

        <div className="space-y-8">
          <section className="bg-indigo-600/10 border border-indigo-500/20 rounded-3xl p-8 h-full">
            <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center mb-6 shadow-xl shadow-indigo-600/20">
              <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <h4 className="text-xl font-black mb-4">Parental Recommendations</h4>
            <p className="text-slate-300 leading-relaxed font-medium">
              {report.recommendations}
            </p>
            <div className="mt-8 pt-8 border-t border-white/10 flex items-center gap-4">
              <img 
                src="https://api.dicebear.com/7.x/bottts/svg?seed=Buddy&backgroundColor=6366f1" 
                alt="AI Buddy" 
                className="w-10 h-10 rounded-full bg-slate-800"
              />
              <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                Generated by TutorBuddy AI <br/> Pedagogical Engine
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};
